version: 2

models:

  - name: stg_local_bike_raw__brands
    description: "Staging table for brands"
    columns:
      - name: brand_id
        description: "Primary key of brands"
        tests:
          - not_null
          - unique

  - name: stg_local_bike_raw__categories
    description: "Staging table for categories"
    columns:
      - name: category_id
        description: "Primary key of categories"
        tests:
          - not_null
          - unique

  - name: stg_local_bike_raw__customers
    description: "Staging table for customers"
    columns:
      - name: customer_id
        description: "Primary key of customers"
        tests:
          - not_null
          - unique
  
  - name: stg_local_bike_raw__products
    description: "Staging table for products"
    columns:
      - name: product_id
        description: "Primary key of products"
        tests:
          - not_null
          - unique

  - name: stg_local_bike_raw__orders
    description: "Staging table for orders"
    columns:
      - name: order_id
        description: "Primary key of orders"
        tests:
          - not_null
          - unique

  - name: stg_local_bike_raw__order_items
    description: "Staging table for order items"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: item_id
        tests:
          - not_null

  - name: stg_local_bike_raw__stocks
    description: "Staging table for stocks"
    columns:
      - name: store_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null

  - name: stg_local_bike_raw__stores
    description: "Staging table for stores"
    columns:
      - name: store_id
        tests:
          - not_null
          - unique

  - name: stg_local_bike_raw__staffs
    description: "Staging table for staffs"
    columns:
      - name: staff_id
        tests:
          - not_null
          - unique


models:
  - name: stg_local_bike_raw__orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_local_bike_raw__customers')
              field: customer_id


